name: Compile assets

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: toml-cli
          version: 0.2.0
          use-tool-cache: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Set version
        shell: bash
        run: |
          toml set Cargo.toml package.version ${{ github.event.release.tag_name }} > Cargo.toml.new
          mv Cargo.toml.new Cargo.toml
      - run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --allow-dirty